<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Julia Fukuyama" />
  <title>Stat 470/670 Lecture 22: Logistic regression with many predictors</title>
  <style type="text/css">
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" type="text/css" media="screen, projection, print"
    href="https://www.w3.org/Talks/Tools/Slidy2/styles/slidy.css" />
  <script
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"
  type="text/javascript"></script>
  <script src="https://www.w3.org/Talks/Tools/Slidy2/scripts/slidy.js"
    charset="utf-8" type="text/javascript"></script>
</head>
<body>
<div class="slide titlepage">
  <h1 class="title">Stat 470/670 Lecture 22: Logistic regression with
many predictors</h1>
  <p class="author">
Julia Fukuyama
  </p>
</div>
<div id="arsenic-in-wells" class="slide section level1">
<h1>Arsenic in wells</h1>
<p>The file <code>wells.dat</code> contains data on 3,020 households in
Bangladesh whose wells had arsenic levels above the national drinking
water standard of 50 micrograms per liter. The variables are:</p>
<ul class="incremental">
<li><p><code>switch</code>: the response: whether or not the household
switched after being encouraged to do so (after high arsenic was
measured.)</p></li>
<li><p><code>arsenic</code>: the arsenic concentration in hundreds of
micrograms per liter.</p></li>
<li><p><code>dist</code>: the distance to the nearest safe well in
meters.</p></li>
<li><p><code>assoc</code>: whether anyone in the household is in a
community association.</p></li>
<li><p><code>educ</code>: the years of education of the head of the
household.</p></li>
</ul>
</div>
<div class="slide section level1">

<p>We load at the data and look at the numerical summary and a pairs
plot:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>wells <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">&quot;../../datasets/wells.dat&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wells)</span></code></pre></div>
<pre><code>##      switch          arsenic           dist             assoc       
##  Min.   :0.0000   Min.   :0.510   Min.   :  0.387   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.820   1st Qu.: 21.117   1st Qu.:0.0000  
##  Median :1.0000   Median :1.300   Median : 36.761   Median :0.0000  
##  Mean   :0.5752   Mean   :1.657   Mean   : 48.332   Mean   :0.4228  
##  3rd Qu.:1.0000   3rd Qu.:2.200   3rd Qu.: 64.041   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :9.650   Max.   :339.531   Max.   :1.0000  
##       educ       
##  Min.   : 0.000  
##  1st Qu.: 0.000  
##  Median : 5.000  
##  Mean   : 4.828  
##  3rd Qu.: 8.000  
##  Max.   :17.000</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(wells)</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-1-1.png" /></p>
<p>As we might expect, distance and education level are positively
associated with switching, while arsenic level is negatively associated.
Surprisingly, the correlation between belong to an association and
switching is negative, though the relationship is very weak.</p>
</div>
<div class="slide section level1">

<p>Distance and arsenic levels should be the best predictors, so let’s
look more closely at the distributions of those variables.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> dist)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">340</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance to nearest safe well (meters)&quot;</span>)</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-2-1.png" /></p>
<p>We see the distribution of distance peaks around 40–60 meters, then
is strongly right-skewed. We should keep the possibility of a
transformation in mind.</p>
</div>
<div class="slide section level1">

<p>Then arsenic:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> arsenic)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="fl">0.25</span>)) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration (100 mg/liter)&quot;</span>)</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-3-1.png" /></p>
<p>There are no observations with arsenic below 0.5, because these are
considered “safe” and the households don’t get advised to switch wells.
Otherwise, the distribution is against strongly right-skewed, suggesting
a transformation.</p>
<p>Note that the scales of <code>dist</code> and <code>arsenic</code>
are quite different. Some authors suggest standardizing the data for
interpretability, so that predictors are on approximately the same
scale. That’s not a bad idea but we will hold off for now.</p>
</div>
<div class="slide section level1">

<p>And finally education:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> educ)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="sc">-</span><span class="fl">0.5</span><span class="sc">:</span><span class="fl">17.5</span>) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Years of education&quot;</span>)</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-4-1.png" /></p>
<p>The distribution is weird. 0 (no education) and 5 (primary school
only) are the magic numbers.</p>
</div>
<div id="starting-off-simple" class="slide section level1">
<h1>Starting off simple</h1>
<p>One way of approaching EDA is to throw everything into your model and
then get rid of terms you don’t need. Another strategy is to start with
simple models and gradually build up to complex models. Let’s take this
second approach for now.</p>
<p>We’ll start by predicting switching, using distance as the only
response. There’s no reason why we can’t try loess:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> <span class="cf">switch</span>)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="dv">0</span>, <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-5-1.png" /></p>
<p>We can interpret the fit as the probability of switching wells, given
the distance to the nearest safe well. There’s a bump for very low
distances (which is probably just noise) and then a decline. We could
play around with the smoothing parameters to get something more
pleasant-looking. Instead, we’ll fit a logistic regression to guarantee
a decreasing relationship.</p>
</div>
<div class="slide section level1">

<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>gg <span class="ot">=</span> <span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> <span class="cf">switch</span>)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="dv">0</span>, <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>gg <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;glm&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-6-1.png" /></p>
<p>The parametric method imposes a functional form on the data. This
aids in interpretability: the fit can now be described in a couple of
parameters, and the weird bump at the beginning is gone. The cost is
some lack of fit: perhaps the probability should decrease more quickly
as the distance gets beyond about 60 meters (remember that water is
heavy and it’s tiring to carry buckets back and forth over long
distances.)</p>
</div>
<div class="slide section level1">

<p>Let’s try the same kind of approach using arsenic concentration as
the sole predictor.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>gg <span class="ot">=</span> <span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> arsenic, <span class="at">y =</span> <span class="cf">switch</span>)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="dv">0</span>, <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>gg <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;glm&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-7-1.png" /></p>
<p>The fits diverge at arsenic levels above about 5. That seems to be
because of a couple of extremely high arsenic observations which led to
switching. Note however that not much of the data has arsenic above 5,
so it remains to be seen how much this matters.</p>
<p>Also note the difference in fits for low levels of arsenic. This is
more worrisome than the difference at high levels because there is
actually a lot of data there. It seems likely that there is a lack of
fit for the low concentrations that logistic regression can’t handle.
We’ll come back to this later.</p>
</div>
<div id="two-predictors" class="slide section level1">
<h1>Two predictors</h1>
<p>We now want to know how the chance of switching depends on distance
and arsenic simulataneously. Before fitting a model, we plot the data to
get a feel for it. We’ll use color to distinguish between households
that switch and households that don’t.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> arsenic, <span class="at">color =</span> <span class="fu">factor</span>(<span class="cf">switch</span>))) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Did they switch?&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#E69F00&quot;</span>, <span class="st">&quot;#56B4E9&quot;</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-8-1.png" /></p>
<p>The <code>alpha = 0.5</code> makes the points slightly transparent,
which can help visually when you have a lot of data. Still, it’s hard to
work out how switching depends on the other two variables from this
graph; that’s why we’re fitting a model. The main thing to take home
from the graph is the lack of data in the top right: we have no
observations at all with both distance above 200 and arsenic above 4, so
we should not try to generalize to this region.</p>
</div>
<div class="slide section level1">

<p>Density plots are actually more useful for comparing the two
distributions, and we can use <code>geom_density2d</code> to make such a
plot:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wells, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> arsenic, <span class="at">color =</span> <span class="fu">factor</span>(<span class="cf">switch</span>))) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density2d</span>() <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Did they switch?&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#E69F00&quot;</span>, <span class="st">&quot;#56B4E9&quot;</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-9-1.png" /></p>
<p>We see here that people who didn’t switch tend to be at lower arsenic
levels and larger distances from the nearest safe well, which makes
sense.</p>
</div>
<div class="slide section level1">

<p>Now we’ll fit a logistic regression using both distance and arsenic
as predictors. We first fit an additive model, i.e. with no
interaction.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>switch.logit <span class="ot">=</span> <span class="fu">glm</span>(<span class="cf">switch</span> <span class="sc">~</span> dist <span class="sc">+</span> arsenic, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> wells)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(switch.logit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = switch ~ dist + arsenic, family = &quot;binomial&quot;, data = wells)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6351  -1.2139   0.7786   1.0702   1.7085  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.002749   0.079448   0.035    0.972    
## dist        -0.008966   0.001043  -8.593   &lt;2e-16 ***
## arsenic      0.460775   0.041385  11.134   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4118.1  on 3019  degrees of freedom
## Residual deviance: 3930.7  on 3017  degrees of freedom
## AIC: 3936.7
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>As always, the coefficients are the most important things here.
According to the model,</p>
<p><span class="math display">\[
\textrm{logit}[P(\textrm{switch}|{\textrm{dist, arsenic}})] = 0.003 -
0.00897 \times \textrm{dist} + 0.4608 \times \textrm{arsenic}.
\]</span></p>
</div>
<div class="slide section level1">

<p>As in the continuous case, we visualize the fit by drawing multiple
curves representing different values of one of the predictors. Let’s
display the switching probability as a function of distance for a few
values of arsenic. Note that when we use the <code>augment()</code>
function, we specify <code>type.predict = "response"</code> to get the
probabilities and not their logits.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dist_df <span class="ot">=</span> <span class="fu">expand.grid</span>(<span class="at">dist =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">339</span>, <span class="at">arsenic =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">2.5</span>, <span class="fl">0.5</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dist_preds <span class="ot">=</span> <span class="fu">augment</span>(switch.logit, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>, <span class="at">newdata =</span> dist_df)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dist_preds, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> .fitted, <span class="at">group =</span> arsenic, <span class="at">color =</span> arsenic)) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_viridis</span>()</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-11-1.png" /></p>
<p>The median arsenic level is 1.3. If arsenic is near the median, the
probability of switching declines from 60-something percent if you’re
right by a safe well to less than 10% if the nearest safe well is
hundreds of meters away.</p>
</div>
<div class="slide section level1">

<p>Now find prediction curves for arsenic for a few different
distances:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>arsenic_df <span class="ot">=</span> <span class="fu">expand.grid</span>(<span class="at">arsenic =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">10</span>, <span class="fl">0.01</span>), <span class="at">dist =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">25</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>arsenic_pred <span class="ot">=</span> <span class="fu">augment</span>(switch.logit, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>, <span class="at">newdata =</span> arsenic_df)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(arsenic_pred, <span class="fu">aes</span>(<span class="at">x =</span> arsenic, <span class="at">y =</span> .fitted, <span class="at">group =</span> dist, <span class="at">color =</span> dist)) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span> <span class="fu">scale_color_viridis</span>()</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-12-1.png" /></p>
<p>The median distance to a safe well is about 37 meters. At that
distance, if the arsenic level is only just over the safety threshold,
it’s about 50–50 whether a household switched. On the other hand, at the
highest levels of arsenic, households will almost certainly switch even
if the nearest safe well is quite far.</p>
</div>
<div id="adding-an-interaction" class="slide section level1">
<h1>Adding an interaction</h1>
<p>We now add an interaction term between distance and arsenic.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>switch_int <span class="ot">=</span> <span class="fu">glm</span>(<span class="cf">switch</span> <span class="sc">~</span> dist <span class="sc">*</span> arsenic, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> wells)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(switch_int)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = switch ~ dist * arsenic, family = &quot;binomial&quot;, data = wells)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7823  -1.2004   0.7696   1.0816   1.8476  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -0.147868   0.117538  -1.258  0.20838    
## dist         -0.005772   0.002092  -2.759  0.00579 ** 
## arsenic       0.555977   0.069319   8.021 1.05e-15 ***
## dist:arsenic -0.001789   0.001023  -1.748  0.08040 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4118.1  on 3019  degrees of freedom
## Residual deviance: 3927.6  on 3016  degrees of freedom
## AIC: 3935.6
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The numbers are a bit hard to interpret. For example, the sign of the
interaction term is negative, but it’s hard to know exactly what this
means (especially since the signs for distance and arsenic go in
different directions.) The interpretation is easier if we just plot
curves.</p>
</div>
<div class="slide section level1">

<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dist_int <span class="ot">=</span> <span class="fu">augment</span>(switch_int, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>, <span class="at">newdata =</span> dist_df)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dist_int, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> .fitted, <span class="at">group =</span> arsenic, <span class="at">color =</span> arsenic)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span> <span class="fu">scale_color_viridis</span>()</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-14-1.png" /></p>
<p>The interaction brings the curves together as distance increases. If
the nearest safe well is close, it makes a big difference whether the
arsenic concentration is just over the limit or much bigger. If the
nearest safe well is far, it makes little difference: people are
unlikely to switch no matter the concentration. The curves meet up
beyond 300 meters, though we only have three observations where the
distance exceeds 300 meters.</p>
</div>
<div class="slide section level1">

<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>arsenic_int_pred <span class="ot">=</span> <span class="fu">augment</span>(switch_int, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>, <span class="at">newdata =</span> arsenic_df)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(arsenic_int_pred, <span class="fu">aes</span>(<span class="at">x =</span> arsenic, <span class="at">y =</span> .fitted, <span class="at">group =</span> dist, <span class="at">color =</span> dist)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span> <span class="fu">scale_color_viridis</span>()</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-15-1.png" /></p>
<p>The curves actually get further apart at first as arsenic increases
(up to a point.) That is, the curves for short distances rise quite
quickly as arsenic increases, while the curves for long distances rise
more slowly. Eventually, for exceptionally high levels of arsenic, the
curves come together (because they can’t go any higher than 1.)</p>
</div>
<div id="lots-of-predictors" class="slide section level1">
<h1>Lots of predictors</h1>
<p>Distance and arsenic are both good predictors and there’s no reason
to think there shouldn’t be an interaction, so keep the interaction
term. Now let’s add <code>assoc</code> and <code>educ</code> to the
model and see if the fit makes sense.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(<span class="cf">switch</span> <span class="sc">~</span> dist <span class="sc">*</span> arsenic <span class="sc">+</span> assoc <span class="sc">+</span> educ, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> wells))</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = switch ~ dist * arsenic + assoc + educ, family = &quot;binomial&quot;, 
##     data = wells)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7303  -1.1892   0.7444   1.0675   1.6987  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -0.291120   0.131427  -2.215  0.02675 *  
## dist         -0.006081   0.002093  -2.905  0.00367 ** 
## arsenic       0.553238   0.069542   7.955 1.79e-15 ***
## assoc        -0.123188   0.076977  -1.600  0.10953    
## educ          0.041948   0.009594   4.372 1.23e-05 ***
## dist:arsenic -0.001612   0.001022  -1.577  0.11482    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4118.1  on 3019  degrees of freedom
## Residual deviance: 3905.4  on 3014  degrees of freedom
## AIC: 3917.4
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Years of education has a positive coefficient, which makes sense. We
can keep that in the model.</p>
<p>Association membership has a <em>negative</em> coefficient, which
doesn’t make causal sense: it would be strange for association
membership to make you <em>less</em> likely to switch wells, unless you
were a member of the Association for Arsenic Being Good for You. If our
sole goal was prediction, we could do a careful cross-validation to see
if association membership did help predict more accurately. Since we’re
doing EDA, we can drop the association term.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(<span class="cf">switch</span> <span class="sc">~</span> dist <span class="sc">*</span> arsenic <span class="sc">+</span> educ, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> wells))</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = switch ~ dist * arsenic + educ, family = &quot;binomial&quot;, 
##     data = wells)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7149  -1.1886   0.7478   1.0689   1.7223  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -0.349044   0.126360  -2.762  0.00574 ** 
## dist         -0.006047   0.002095  -2.886  0.00390 ** 
## arsenic       0.555367   0.069531   7.987 1.38e-15 ***
## educ          0.042306   0.009581   4.415 1.01e-05 ***
## dist:arsenic -0.001629   0.001023  -1.592  0.11145    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4118.1  on 3019  degrees of freedom
## Residual deviance: 3907.9  on 3015  degrees of freedom
## AIC: 3917.9
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="slide section level1">

<p>We now add the remaining two-way interactions. In general, if you
only have a few terms, you might as well include all the two-way
interactions unless you have a good reason not to.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>switch_model <span class="ot">=</span> <span class="fu">glm</span>(<span class="cf">switch</span> <span class="sc">~</span> dist <span class="sc">+</span> arsenic <span class="sc">+</span> educ <span class="sc">+</span> dist<span class="sc">:</span>arsenic <span class="sc">+</span> dist<span class="sc">:</span>educ <span class="sc">+</span> arsenic<span class="sc">:</span>educ,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> wells)</span></code></pre></div>
</div>
<div class="slide section level1">

<p>At this point our model is too complicated for it to be worth trying
to interpret the numbers. Let’s extract the fitted values and residuals,
and plot the latter against the former. Note that the default of
<code>augment()</code> is to extract the deviance residuals instead of
the response residuals, if you know about and prefer deviance residuals
you can specify them instead.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>switch_model_df <span class="ot">=</span> <span class="fu">augment</span>(switch_model, <span class="at">type.residuals =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(switch_model_df, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">degree =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Fitted values&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-19-1.png" /></p>
<p>The points on the plot fall exactly on two lines, so look at the
smooth instead. We see there’s a little bit of waviness. This is fairly
typical for logistic regression: there’s no reason why the relationship
between probability and the predictors should have that exact functional
form. But the improvement in fit you get from fitting a nonparametric
model is fairly small.</p>
</div>
<div class="slide section level1">

<p>Now plot the residuals against distance. What we’re looking for here
is whether the function form is correct, or whether we need more
flexibility in how we use distance to predict switching.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(switch_model_df, <span class="fu">aes</span>(<span class="at">x =</span> dist, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">degree =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Distance from nearest safe well&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-20-1.png" /></p>
<p>There’s a wiggle, but this is basically fine – the zero line is
enclosed in the confidence band.</p>
</div>
<div class="slide section level1">

<p>Now let’s do the same plot with arsenic on the <span
class="math inline">\(x\)</span>-axis:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(switch_model_df, <span class="fu">aes</span>(<span class="at">x =</span> arsenic, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">degree =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-21-1.png" /></p>
<p>This is much worse. The curve is too low, then rises too high, then
declines again. In fact, the extreme left hand side is the biggest
problem, since the lack is fit is real and the data is dense there. The
negative average residual there means that for arsenic levels just over
the threshold, the probability of switching is <em>overestimated</em>
(negative average residuals occur when there are more zeroes in the
response than the model expects.)</p>
</div>
<div class="slide section level1">

<p>Education isn’t that interesting since the effect is much smaller,
but let’s do it for completeness.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(switch_model_df, <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">degree =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Years of education&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-22-1.png" /></p>
<p>Again, the fit is imperfect.</p>
</div>
<div class="slide section level1">

<p>Remember when we said we might need to transform? The last couple of
graphs suggest that while a transformation of distance is unnecessary, a
transformation of arsenic is. A transformation of education would
probably help too, but since the variable is weird and not that
important we won’t bother. We’ll take the log arsenic and refit the
model.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>wells<span class="sc">$</span>log.arsenic <span class="ot">=</span> <span class="fu">log</span>(wells<span class="sc">$</span>arsenic)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>log_arsenic_model <span class="ot">=</span> <span class="fu">glm</span>(<span class="cf">switch</span> <span class="sc">~</span> dist <span class="sc">+</span> log.arsenic <span class="sc">+</span> educ <span class="sc">+</span> dist<span class="sc">:</span>log.arsenic <span class="sc">+</span> dist<span class="sc">:</span>educ <span class="sc">+</span> log.arsenic<span class="sc">:</span>educ, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> wells)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>log_arsenic_model_df <span class="ot">=</span> <span class="fu">augment</span>(log_arsenic_model, <span class="at">type.residuals =</span> <span class="st">&quot;pearson&quot;</span>, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
</div>
<div class="slide section level1">

<p>Now plot the residuals of this new model against log arsenic:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(log_arsenic_model_df, <span class="fu">aes</span>(<span class="at">x =</span> log.arsenic, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">degree =</span> <span class="dv">1</span>))  <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Log arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-22-fig/unnamed-chunk-24-1.png" /></p>
<p>It’s a lot better. I’m fairly happy with the model at this point.</p>
</div>
<div class="slide section level1">

<p>Let’s take a look at the fit. Fix education at its median, and draw
arsenic curves for several distances:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>switch_grid <span class="ot">=</span> <span class="fu">expand.grid</span>(<span class="at">arsenic =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">10</span>, <span class="fl">0.01</span>), <span class="at">dist =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">25</span>), <span class="at">educ =</span> <span class="dv">5</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>switch_grid<span class="sc">$</span>log.arsenic <span class="ot">=</span> <span class="fu">log</span>(switch_grid<span class="sc">$</span>arsenic)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>log_arsenic_pred_grid <span class="ot">=</span> <span class="fu">augment</span>(log_arsenic_model, <span class="at">newdata =</span> switch_grid,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>, <span class="at">type.residuals =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(log_arsenic_pred_grid, <span class="fu">aes</span>(<span class="at">x =</span> arsenic, <span class="at">y =</span> .fitted, <span class="at">group =</span> dist, <span class="at">color =</span> dist)) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>) <span class="sc">+</span> <span class="fu">scale_color_viridis</span>()</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-25-1.png" /></p>
</div>
<div class="slide section level1">

<p>There are 3! ways you can assign the three variables to <span
class="math inline">\(x\)</span>-axis, conditioning variable, and fixed.
You probably get the idea at this point, though, so let’s just do one
more:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>switch_grid_2 <span class="ot">=</span> <span class="fu">expand.grid</span>(<span class="at">arsenic =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">10</span>, <span class="fl">0.01</span>), <span class="at">dist =</span> <span class="fu">median</span>(wells<span class="sc">$</span>dist), <span class="at">educ =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">10</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>switch_grid_2<span class="sc">$</span>log.arsenic <span class="ot">=</span> <span class="fu">log</span>(switch_grid_2<span class="sc">$</span>arsenic)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>log_arsenic_pred_grid_2 <span class="ot">=</span> <span class="fu">augment</span>(log_arsenic_model, <span class="at">newdata =</span> switch_grid_2,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>, <span class="at">type.residuals =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(log_arsenic_pred_grid_2,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> arsenic, <span class="at">y =</span> .fitted, <span class="at">group =</span> educ, <span class="at">color =</span> <span class="fu">factor</span>(educ))) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Arsenic concentration&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Probability of switching&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Education&quot;</span>) <span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#999999&quot;</span>, <span class="st">&quot;#E69F00&quot;</span>, <span class="st">&quot;#56B4E9&quot;</span>),</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;0 years&quot;</span>, <span class="st">&quot;5 years&quot;</span>, <span class="st">&quot;10 years&quot;</span>))</span></code></pre></div>
<p><img src="lecture-22-fig/unnamed-chunk-26-1.png" /></p>
</div>
<div id="improving-the-model" class="slide section level1">
<h1>Improving the model</h1>
<p>If you really care about prediction but still want to be able to
interpret the model, try a nonparametric model such as a generalized
additive model (GAM) or loess. To overgeneralize, GAM is often
better/easier when you have lots of predictors, while loess is often
better/easier when you have complex interactions. You can learn more
about these in S425/625.</p>
<p>If you really, really care about predictions then you can use machine
learning techniques. The improvement in prediction is usually quite
small, however, and you’ll lose a lot or all the interpretability.</p>
</div>
</body>
</html>
