<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Julia Fukuyama" />
  <title>Stat 470/670 Lecture 15: Binary data and logistic regression</title>
  <style type="text/css">
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" type="text/css" media="screen, projection, print"
    href="https://www.w3.org/Talks/Tools/Slidy2/styles/slidy.css" />
  <script
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"
  type="text/javascript"></script>
  <script src="https://www.w3.org/Talks/Tools/Slidy2/scripts/slidy.js"
    charset="utf-8" type="text/javascript"></script>
</head>
<body>
<div class="slide titlepage">
  <h1 class="title">Stat 470/670 Lecture 15: Binary data and logistic
regression</h1>
  <p class="author">
Julia Fukuyama
  </p>
</div>
<div id="problem-setup" class="slide section level2">
<h1>Problem setup</h1>
<p>We are interested in understanding voting patterns, and in particular
how vote for president is related to income.</p>
<p>There is data on this topic in the <a
href="http://jfukuyama.github.io/teaching/stat670/notes/anes.csv">ANES
dataset</a>: for each election, they have demographic information on a
subset of voters plus information about how they voted in the
presidential elections.</p>
<p>The variables here have particularly uninformative names, but the
ones we are interested in describe the year, income, and presidential
vote. They are coded as:</p>
<ul>
<li>Year: VCF0004</li>
</ul>
<ul>
<li>Income: VCF0114</li>
</ul>
<ul>
<li>Vote: VCF0704a</li>
</ul>
<p>The primary difference between our task here and the modeling that
we’ve done earlier in the semester is that the variable we’re trying to
predict, vote, is binary. That is, it only takes two values (here vote
for Republicans vs. vote for Democrats) instead of taking as a value any
real number. This turns out to be enough of a difference that we need a
new modeling technique.</p>
</div>
<div class="slide section level2">

<p>Income is measured on a scale from 1 to 5:</p>
<p>1: 0 to 16 percentile</p>
<p>2: 17 to 33 percentile</p>
<p>3: 34 to 67 percentile</p>
<p>4: 68 to 95 percentile</p>
<p>5: 96 to 100 percentile</p>
<p>Using percentiles allows comparability between years. Also note that
this is really an ordinal variable but we might find some advantages in
treating it as quantitative.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ANES <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;anes.csv&quot;</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>income <span class="ot">=</span> ANES<span class="sc">$</span>VCF0114</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(income)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    1.00    2.00    3.00    2.87    4.00    5.00    5449</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(income) <span class="sc">/</span> <span class="fu">length</span>(income)</span></code></pre></div>
<pre><code>## income
##          1          2          3          4          5 
## 0.15804751 0.15120779 0.29807821 0.25447084 0.04729414</code></pre>
</div>
<div class="slide section level2">

<p>Next we need the year for each observation. This is VCF0004.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>year <span class="ot">=</span> ANES<span class="sc">$</span>VCF0004</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(year)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1948    1970    1986    1985    2002    2016</code></pre>
</div>
<div class="slide section level2">

<p>The coding is that “1” means the Democrat, “2” means the Republican,
and “0” or “NA” means some other outcome. We want everything to be coded
as 0, 1, or NA (using 0/1 coding is the standard way to code binary
variables for logistic regression).</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>vote <span class="ot">=</span> ANES<span class="sc">$</span>VCF0704a</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="do">##  First, change the zeroes to NA’s:</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>vote[vote <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">=</span> <span class="cn">NA</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Then, to go from 2 representing Republican and 1 representing Democrat to 1 = Republican, 0 = Democrat, we just have to subtract 1</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>vote <span class="ot">=</span> vote <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vote)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    0.00    0.00    0.48    1.00    1.00   35118</code></pre>
<p>The variable really represents the fraction of the two-party vote
that was for Republicans now, so for clarity let’s just rename it as
such.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Republican <span class="ot">=</span> vote</span></code></pre></div>
</div>
<div class="slide section level2">

<p>Let’s put everything in a data frame, and then filter to just
presidential election years:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ANES_df <span class="ot">=</span> <span class="fu">data.frame</span>(year, income, Republican)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ANES_df <span class="ot">=</span> <span class="fu">filter</span>(ANES_df, year <span class="sc">%in%</span> <span class="fu">seq</span>(<span class="dv">1948</span>, <span class="dv">2016</span>, <span class="dv">4</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ANES_df)</span></code></pre></div>
<pre><code>##       year          income        Republican   
##  Min.   :1948   Min.   :1.000   Min.   :0.000  
##  1st Qu.:1972   1st Qu.:2.000   1st Qu.:0.000  
##  Median :1992   Median :3.000   Median :0.000  
##  Mean   :1989   Mean   :2.861   Mean   :0.481  
##  3rd Qu.:2012   3rd Qu.:4.000   3rd Qu.:1.000  
##  Max.   :2016   Max.   :5.000   Max.   :1.000  
##                 NA&#39;s   :2524    NA&#39;s   :14394</code></pre>
</div>
<div id="visualizing-the-relationship-with-one-predictor"
class="slide section level2">
<h1>Visualizing the relationship with one predictor</h1>
<p>The first question we can ask is about the relationship between
income and the probability of voting Republican in 1992. Let’s start off
just by plotting the two points. It turns out that this isn’t trivial
because the variables are categorical, and we need to do some work to
get anything useful. Jittering helps with categorical variables, and we
use it here:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ANES92 <span class="ot">=</span> <span class="fu">subset</span>(ANES_df, year <span class="sc">==</span> <span class="dv">1992</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ANES92, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> Republican)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="lecture-15-fig/unnamed-chunk-6-1.png" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ANES92, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> Republican)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.1</span>, <span class="at">width =</span> <span class="fl">0.25</span>, <span class="at">size =</span> .<span class="dv">7</span>)</span></code></pre></div>
<p><img src="lecture-15-fig/unnamed-chunk-6-2.png" /></p>
<p>The jittered plot is ok, but here it’s actually more useful to
compute the fraction of the vote going to Republicans and either look at
the table or plot those values.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">republican_fraction_by_income =</span> ANES92 <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">group_by</span>(income) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarise</span>(<span class="at">republican_fraction =</span> <span class="fu">mean</span>(Republican, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   income republican_fraction
##    &lt;int&gt;               &lt;dbl&gt;
## 1      1               0.267
## 2      2               0.345
## 3      3               0.404
## 4      4               0.488
## 5      5               0.532
## 6     NA               0.433</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">## zero values for income mean missing</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(republican_fraction_by_income, income <span class="sc">!=</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> republican_fraction))</span></code></pre></div>
<p><img src="lecture-15-fig/unnamed-chunk-7-1.png" /></p>
</div>
<div id="how-could-we-model-this-relationship"
class="slide section level2">
<h1>How could we model this relationship?</h1>
<p>This gives the proportion (out of major party voters) who voted for
Bush for each income group. Aside from group zero, which represents
missing values of income, we see a strictly increasing pattern. How do
we model this? Three options (not the only three) include:</p>
<ol style="list-style-type: decimal">
<li>Linear regression with income as a numerical predictor.</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Logistic regression with income as a numerical predictor.</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li>Regression with income as a categorical (factor) predictor. (In this
linear and logistic give identical predictions.)</li>
</ol>
</div>
<div class="slide section level2">

<p>Method 1 is the easiest to interpret: we get a slope that directly
tells us the change in model probability of voting Republican as income
goes up one category. However, linear regression for binary responses
has two big limitations:</p>
<ul>
<li>The technical limitation is that it only works well when
probabilities are far from 0 and 1. Otherwise, if <span
class="math inline">\(x\)</span> is unbounded, you can end up with
negative probabilities or probabilities greater than 1.</li>
</ul>
<ul>
<li>There is also a social limitation in that statisticians will be
quite upset with you and your work if you use linear regression to model
binary data.</li>
</ul>
<p>Method 3 isn’t really a model at all: it just returns the proportion
within each category who voted for Bush, the same as our
<code>summarise()</code> call gave us above. There’s something to be
said for not fitting restrictive models when you don’t have to. However,
if our goal is to fit more complex models or make comparisons between
different sets of data, as it eventually will be, then some degree of
simplification may be useful to understand the patterns in the data. Or
we might fit a simplifying model first, then go back and look at the
data in more detail and see if there are any important features our
model missed. That will be our basic approach here.</p>
<p>Method 2, logistic regression, should work well. It does require
treating a predictor that isn’t inherently a numeric variable as
numeric, and requires a parametric form (effects are linear on a logit
scale.) However, most of the time, doing this is reasonable as long as
the pattern of the probability with <span
class="math inline">\(x\)</span> is monotonic and as long as predictive
accuracy is not the sole goal.</p>
</div>
<div id="logistic-regression-with-one-predictor"
class="slide section level2">
<h1>Logistic regression with one predictor</h1>
<p>We fit such a logistic regression using income as a quantitative
variable and omitting missing values. Logistic regression is a special
case of a GLM, so we use the <code>glm()</code> function; specifying a
binomial family fits a logistic regression by default. Firstly, we can
just add the fitted curve to the jittered plot:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ANES92, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> Republican)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.1</span>, <span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;glm&quot;</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="lecture-15-fig/unnamed-chunk-8-1.png" /></p>
<p>We can also fit it explicitly:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>logit_92 <span class="ot">=</span> <span class="fu">glm</span>(Republican <span class="sc">~</span> income, <span class="at">family =</span> binomial, <span class="at">data =</span> ANES92)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_92)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Republican ~ income, family = binomial, data = ANES92)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2733  -1.0235  -0.9086   1.2096   1.6069  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.26750    0.17789  -7.125 1.04e-12 ***
## income       0.29802    0.05379   5.541 3.01e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1719.1  on 1266  degrees of freedom
## Residual deviance: 1687.2  on 1265  degrees of freedom
##   (1218 observations deleted due to missingness)
## AIC: 1691.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The summary gives a lot of information; we’ll focus on the
coefficients. The summary tells us that</p>
<p><span class="math display">\[
\text{logit}[P(\text{Republican})]=−1.27+0.298\times \text{income}
\]</span></p>
<p>where the logit function is</p>
<p><span class="math display">\[
\text{logit}(x)=\text{log}_e [x/(1−x)]
\]</span></p>
<p>To find <span class="math inline">\(P(\text{Republican})\)</span>, we
invert the logit:</p>
<p><span class="math display">\[
P(\text{Republican})=\text{logit}^{-1} (-1.27 + 0.298 \times
\text{income})
\]</span></p>
<p>where <span class="math display">\[
\text{logit}^{-1}(y) = \frac{e^y}{1+e^y}
\]</span></p>
<p>For a quick and dirty interpretation, the “divide by 4” rule is
useful: the maximum change in probability associated with a one unit
change in <span class="math inline">\(x\)</span> is the coefficient of
<span class="math inline">\(x\)</span> divided by four. So going one
income group changes the model probability by up to about 7.5%. This
looks like it’s about the increase in the curve from income group 4 to
group 5.</p>
<p>We can check how good the approximation is:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## the package boot has the inv.logit function</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="do">## P(Republican) evaluated at income = 4</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">inv.logit</span>(<span class="sc">-</span><span class="fl">1.27</span> <span class="sc">+</span> <span class="fl">0.298</span> <span class="sc">*</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.4805099</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">## P(Republican) evaluated at income = 5</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inv.logit</span>(<span class="sc">-</span><span class="fl">1.27</span> <span class="sc">+</span> <span class="fl">0.298</span> <span class="sc">*</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.5547792</code></pre>
</div>
<div id="fitting-a-series-of-regressions" class="slide section level2">
<h1>Fitting a series of regressions</h1>
<p>We’re not just interested in 1992. We want to know the relationship
between income and vote for every Presidential election we have data for
– is the relationship similar for every election, or are some elections
different? Has there been a consistent change over time?</p>
<p>In programming terms, the easiest way to fit the same model on many
subsets of the data is to write a function that subsets the data and
fits the model, then to write a for loop to fit the model for each
subset. There are much more computationally efficient approaches, but
otherwise more efficiency usually isn’t worth the effort.</p>
<p>Here’s a function to fit our weighted logistic regression of vote on
income for any given year.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>logit_ANES_subset <span class="ot">=</span> <span class="cf">function</span>(my_year, data) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="do">## newdata = the subset of the data corresponding the year in question</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    newdata <span class="ot">=</span> <span class="fu">subset</span>(data, year <span class="sc">==</span> my_year)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="do">## model where the data are a subset corresponding to my_year</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    model <span class="ot">=</span> <span class="fu">glm</span>(Republican <span class="sc">~</span> income, <span class="at">family =</span> binomial, </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> newdata)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="do">## getting just the output from the logistic regression fit that we need</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    output <span class="ot">=</span> <span class="fu">c</span>(my_year, <span class="fu">summary</span>(model)<span class="sc">$</span>coef[<span class="dv">2</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(output)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The function returns the year, the model’s coefficient for income,
and the standard error of that coefficient. We shouldn’t take the
standard error too literally, because we haven’t accounted for the
complex design of the ANES surveys.</p>
<p>Let’s test the function out on 1992 (Bush-Clinton).</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logit_ANES_subset</span>(<span class="at">my_year =</span> <span class="dv">1992</span>, <span class="at">data =</span> ANES_df)</span></code></pre></div>
<pre><code>##                  Estimate   Std. Error 
## 1.992000e+03 2.980249e-01 5.378931e-02</code></pre>
</div>
<div class="slide section level2">

<p>Once we’ve checked that it works, we can loop over every presidential
election year in our dataset: every four years between 1948 and
2012:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>years <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1948</span>, <span class="dv">2016</span>, <span class="dv">4</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(years)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>income_by_year <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n), <span class="at">income_coef =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n), <span class="at">income_se =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (J <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    my_year <span class="ot">=</span> years[J]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    income_by_year[J, ] <span class="ot">=</span> <span class="fu">logit_ANES_subset</span>(<span class="at">my_year =</span> my_year, <span class="at">data =</span> ANES_df)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div class="slide section level2">

<p>We’ll display the results using <code>ggplot</code>.
<code>geom_errorbar()</code> lets us add one standard error bounds. We
shouldn’t take these too literally, just use them to get a ballpark idea
of uncertainty.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>gg <span class="ot">=</span> <span class="fu">ggplot</span>(income_by_year, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> income_coef, <span class="at">ymin =</span> income_coef <span class="sc">-</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    income_se, <span class="at">ymax =</span> income_coef <span class="sc">+</span> income_se))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>gg <span class="sc">+</span> <span class="fu">geom_errorbar</span>(<span class="at">width=</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Coefficient of income in linear model&quot;</span>)</span></code></pre></div>
<p><img src="lecture-15-fig/unnamed-chunk-14-1.png" /></p>
<p>The income coefficient is positive for every election, meaning richer
people were more likely to vote Republican every time (though 1960 was
close.) The general trend was an increase in the income coefficient from
1952 to 1984, then a leveling-off. There was a huge drop from 1948 to
1952; unfortunately we don’t have data from before 1948 to know if the
election was typical.</p>
</div>
<div id="less-modeling-more-detail" class="slide section level2">
<h1>Less modeling, more detail</h1>
<p>In our regressions, we treated income as a quantitative variable. A
simpler approach would be to treat it as a factor, and simply track the
weighted proportion of each income group that (two-party) voted
Republican by year. Again, this is easiest to program (if inefficient)
using a for loop.</p>
<p>To find means, I used use <code>mean()</code> in conjunction with
<code>summarise()</code> in dplyr. Let’s first work out how to do it for
the 1992 data.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">group_by</span>(ANES92, <span class="fu">factor</span>(income)), <span class="at">prop_Republican =</span> <span class="fu">mean</span>(Republican, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   `factor(income)` prop_Republican
##   &lt;fct&gt;                      &lt;dbl&gt;
## 1 1                          0.267
## 2 2                          0.345
## 3 3                          0.404
## 4 4                          0.488
## 5 5                          0.532
## 6 &lt;NA&gt;                       0.433</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>income_prop <span class="ot">=</span> ANES_df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(income, year) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">prop_Republican =</span> <span class="fu">mean</span>(Republican, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;income&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## clean up a bit</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>income_prop <span class="ot">=</span> income_prop <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="do">## making income an ordered factor will give a nice color scale for us later</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">income_ord =</span> <span class="fu">factor</span>(income, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">ordered =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</div>
<div class="slide section level2">

<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>gg <span class="ot">=</span> <span class="fu">ggplot</span>(income_prop, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> prop_Republican, <span class="at">group =</span> income_ord, <span class="at">color =</span> income_ord)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>()</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>gg <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Proportion of two-party vote</span><span class="sc">\n</span><span class="st">for Republicans&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">&quot;Income percentile&quot;</span>)</span></code></pre></div>
<p><img src="lecture-15-fig/unnamed-chunk-17-1.png" /></p>
<p>We now have a bit more detail on the trends and the aberrant
results.</p>
<ul>
<li>The top income group is reliably the most Republican, but the bottom
income group isn’t always the most Democratic (although it was in the
middle part of the time period.)</li>
</ul>
<ul>
<li>In 1948 there were pretty big differences between income groups, but
in the 1950s the differences between all groups except the richest were
small. It’s guess work whether 1948 was an aberration or whether the
small income differences from 1952 to 1968 were historically unusual
(though I suspect it’s the latter.)</li>
</ul>
<ul>
<li>The big coefficient for 1964 (compared to the elections before and
after) might be in part an artifact of the logit scale.</li>
</ul>
<ul>
<li>In 2008 there really was a big difference between income group,
which might be attributable to the financial crisis.</li>
</ul>
<ul>
<li>Precipitous drop in fraction of the highest-income group voting for
Republicans. Possibly education polarization.</li>
</ul>
</div>
<div class="slide section level2">

<p>We can also draw lines to connect income groups by year. Because
there are so many different years, we’ll facet them rather than color
them.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(income_prop, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> prop_Republican)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> year, <span class="at">ncol =</span> <span class="dv">6</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Proportion of two-party vote for Republican&quot;</span>)</span></code></pre></div>
<p><img src="lecture-15-fig/unnamed-chunk-18-1.png" /></p>
<p>This yields less insight, but still has interesting features: notably
the big magnitude of the uptick in Republicanism for the highest income
group for almost every year.</p>
</div>
<div id="data-summaries-vs.-data-models" class="slide section level2">
<h1>Data summaries vs. data models</h1>
<p>Both data summaries (like our last plot) and models (like our
logistic regressions) have their uses.</p>
<ul>
<li>Data summaries require fewer assumptions, and often give you a
fuller picture than a model. However, they can be noisy or just too
complicated to easily get a grip on.</li>
</ul>
<ul>
<li>Models require assumptions, so in addition to being reductive,
there’s more potential for things to go horribly wrong. However, models
can be a easy way into the data: everything gets summarized in a couple
of parameters, and you can put your effort into understanding what those
parameters really mean. Furthermore, complexity can easily be added to
models – for example, it’s easy to build a logistic regression model
with multiple predictors (as we’ll see in the next lecture.)</li>
</ul>
<p>In practice, going back and forth between models and data summaries,
as we did here, is often very useful in exploratory work. Models can
usefully simplify the data so you can get the big picture. Then you can
look a fuller data summary and bear in results that the big picture
doesn’t explain.</p>
</div>
</body>
</html>
